# SportsOracle Project Configuration

# Embedding
embedding_model: all-mpnet-base-v2
embedding_batch_size: 64

# BERTopic/Clustering
bertopic_min_topic_size: 10
hdbscan_min_cluster_size: 10
hdbscan_min_samples: 2
hdbscan_metric: euclidean
umap_n_neighbors: 15
umap_n_components: 5
umap_min_dist: 0.1
umap_metric: cosine
vectorizer_max_features: 2000
vectorizer_ngram_range: [1, 3]

# Summarization
summary_model: facebook/bart-large-cnn
summary_max_length: 80
summary_min_length: 10
top_k_titles: 5

# Categories to process
categories: [nba, soccer] 